### ISSUE TITLE
No plist created

### ISSUE THREAD

**Issue by JulesMoorhouse** [MartinP7r/AckGen#1]
Hi,

I believe I've followed the instructions correctly.

My Build log doesn't show an error, but I do have some comments..

```
[1/1] Planning build
[1/1] Planning build

* Build Completed!
Generating Acknowledgements file

PhaseScriptExecution Run\ Script\ -\ AckGen /Users/jm/Library/Developer/Xcode/DerivedData/MyApp-gzdxsjfyidrbogbyigwwikraorls/Build/Intermediates.noindex/PainMedsBuddy.build/Debug-iphonesimulator/MyApp/Script-88E930A02760A51600A98708.sh (in target 'MyApp' from project 'MyApp')
```

Any ideas, what might be happening ?

Thanks,

Jules

**Comment by MartinP7r** [comment]
Hello @JulesMoorhouse!  
Thank you for trying this out.  

I'm not entirely sure from that warning message.  
However, I recently had a problem with newer Xcode versions myself and found that the run script as it is described in the README might not work. Could you try it as below (only change is the line `SDKROOT=...`) and tell me whether that fixed it?

```swift
DIR=$PROJECT_TEMP_DIR/../../../SourcePackages/checkouts/AckGen
if [ -d "$DIR" ]; then
  cd $DIR
  SDKROOT=(xcrun --sdk macosx --show-sdk-path)
  swift run ackgen
else
  echo "warning: AckGen not found. Please install the package via SPM (https://github.com/MartinP7r/AckGen#installation)"
fi
```

**Comment by JulesMoorhouse** [comment]
👍

Thanks.
