### ISSUE TITLE
Suggestion: Package title

### ISSUE THREAD

**Issue by JulesMoorhouse** [MartinP7r/AckGen#2]
Hey,

Just a suggestion..

How about adding the name of the package as a title above the acknowledgment content?

Nice time saver 👍 

Thanks,

Jules.

**Comment by MartinP7r** [comment]
Sorry, I'm a little occupied due to Christmas vacation.
Great idea! I'll add this as soon as I can.

Merry Christmas!

I'll

**Comment by MartinP7r** [comment]
Oh!  
Thank you so much for the contribution!

**Comment by MartinP7r** [comment]
Let me bump the version after merge.
