### ISSUE TITLE
Todo: Add non-SPM licenses separately

### ISSUE THREAD

**Issue by JulesMoorhouse** [MartinP7r/AckGen#3]
HI,

I've just seen this `Add non-SPM licenses separately` on the Todo list.

I really need this functionality now.
I guess as a temporary solution would be to add it by hand and not run the AckGenCli too often.

Although I might have to fork and extend it and do a PR.

How would you envisage this working ?

I'm thinking a separate plist for these license.
And a check to see if it exists and combine it.

Jules.

EDIT:
Hmmm, isn't there a `xcodeproj` file ?
EDIT2:
Ahhh ‘swift build’ interesting 🤔

**Comment by MartinP7r** [comment]
Hi @JulesMoorhouse,  
really sorry for the late reply. I was occupied with work and family matters and on top of it my notifications here were set to `Participating and @mention` 😢 

> I guess as a temporary solution would be to add it by hand and not run the AckGenCli too often.

You can always just add them as a plist that you provided separately, combining it with the automatically generated one before you pass it to your UI

Honestly I don't think I will have the time to work on this in the near future. But I'll let you knew if I can.

**Comment by MartinP7r** [comment]
I'm closing this for now.
