### ISSUE TITLE
Fix README: Uncheck "ackgen" command line tool when adding SPM as dependency

### ISSUE THREAD

**Issue by appdev-exaring** [MartinP7r/AckGen#5]
The README should note that when adding AckGen as a dependency, you should _not_ check the "ackgen" Executable part.

If you do so, the build for a non-macOS-Target (iOS, tvOS etc.) fails with the error `unable to resolve product type 'com.apple.product-type.tool' for platform 'iphonesimulator'` (or `unable to resolve product type 'com.apple.product-type.tool' for platform 'appletvsimulator'` etc.)

**Comment by MartinP7r** [comment]
Thank you for your contribution.  
To be honest, that could be considered out of the scope of a README, though.
